//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffe.CDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTheCoffeeEntities : DbContext
    {
        public DBTheCoffeeEntities()
            : base("name=DBTheCoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria1> Categoria1 { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Mesero> Mesero { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<rol_usuario> rol_usuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<DiaDeTrabajo> DiaDeTrabajo { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Movimiento_Caja> Movimiento_Caja { get; set; }
        public virtual DbSet<Turno_Caja> Turno_Caja { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Venta_Detalle> Venta_Detalle { get; set; }
    }
}
