//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffe.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_Caja
    {
        public int id_movimiento { get; set; }
        public string tipo_movimiento { get; set; }
        public double monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string descripcion { get; set; }
        public int id_turno { get; set; }
        public int id_caja { get; set; }
    
        public virtual Turno_Caja Turno_Caja { get; set; }
    }
}
