//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffe.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Turno_Caja = new HashSet<Turno_Caja>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string contraseña { get; set; }
        public string usuario1 { get; set; }
        public string telefono { get; set; }
        public string apellido { get; set; }
        public bool estado { get; set; }
        public int id_rol { get; set; }
        public string avatar { get; set; }
    
        public virtual rol_usuario rol_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno_Caja> Turno_Caja { get; set; }
        public string nombreCompleto
        {
            get
            {
                return $"{nombre} {apellido}";
            }
        }
        public string NombreRol
        {
            get { return rol_usuario != null ? rol_usuario.descripcion : "Sin rol"; }
        }

    }
}
